app/app/urls.py
from django.conf.urls import patterns, include, url
from django.conf.urls.static import static
from django.conf import settings
from explore import views
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'app.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),
    url(r'^$', 'explore.views.home'),
    # url(r'^$', views.HomeView.as_view()),
    url(r'^item/(?P<pk>\d+)/(?P<color_pk>\d+)/(?P<seller_pk>\d+)/$', 'explore.views.item'),
    url(r'^feedback/$', 'explore.views.feedback'),
    url(r'^main/', include('explore.urls')),
    url(r'^cart/', include('cart.urls')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^checkpin/$', 'explore.views.checkpin'), 
    url(r'^review/(?P<pk>\d+)/$', 'explore.views.review'),
    url(r'^accounts/', include('allauth.urls')),	
) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

app/core/models.py
from django.db import models
from core.utils import get_upload_file_path
from django.utils.translation import ugettext_lazy as _
from django.contrib.auth.models import User

# Create your models here.
class Category(models.Model):
    category = models.CharField(_('Category'), max_length=50)
    parent = models.ForeignKey('self', blank=True, null=True, related_name='child')
    is_active = models.BooleanField(_("Active"), default=True)
    related_categories = models.ManyToManyField('self', blank=True, null=True)

    class Meta:
        verbose_name_plural = 'Category'

    def __unicode__(self):
        return self.category

class Colour(models.Model):
    colour = models.CharField(_('Colour'), max_length=50)

    class Meta:
        verbose_name_plural = 'Colour'

    def __unicode__(self):
        return self.colour

class Size(models.Model):
    size = models.CharField(_('Size'), max_length=6)

    class Meta:
        verbose_name_plural = 'Size'

    def __unicode__(self):
        return self.size

class Seller(models.Model):
    name = models.CharField(_('Name'), max_length=50)
    address = models.TextField(_('Address'), max_length=50)
    email = models.EmailField(_('Email Address'), max_length=100)
    contactno = models.CharField(_('Contact No.'), max_length=10)

    class Meta:
        verbose_name_plural = 'Seller'

    def __unicode__(self):
        return self.name

class Item(models.Model):
    new_arrival = models.BooleanField(_('New Arrival'))  
    created = models.DateField(_('Created'), max_length=50)
    item_name = models.CharField(_('Item'), max_length=50)
    description = models.TextField(_('Description'), max_length=50)
    fk_color = models.ManyToManyField(Colour)
    fk_size = models.ManyToManyField(Size)
    items_in_stock = models.DecimalField(_("Number in stock"),  max_digits=18, decimal_places=6, default='0')
    total_sold = models.DecimalField(_("Total sold"),  max_digits=18, decimal_places=6, default='0')
    instock = models.BooleanField(_('Instock'), max_length=50)
    fk_seller = models.ManyToManyField(Seller)
    fk_type = models.ManyToManyField(Category)
    related_items = models.ManyToManyField('self', blank=True, null=True, verbose_name=_('Related Items'))
    also_purchased = models.ManyToManyField('self', blank=True, null=True, verbose_name=_('Previously Purchased'))

    class Meta:
        verbose_name_plural = 'Item'

    def __unicode__(self):
        return self.item_name

class Price(models.Model):
    item = models.ForeignKey(Item)
    price = models.CharField(_('Price'), max_length=9)
    discount = models.CharField(_('Discount'), max_length=5)
    cod = models.BooleanField(_('COD'), max_length=50)
    fk_seller = models.ForeignKey(Seller)
    fk_color = models.ForeignKey(Colour)
    fk_size = models.ForeignKey(Size)

    class Meta:
        verbose_name_plural = 'Price'

    def __unicode__(self):
        return self.price

class Itemimage(models.Model):
    item = models.ForeignKey(Item)
    color = models.ForeignKey(Colour)
    image = models.ImageField(_('Image'), upload_to=get_upload_file_path)

    class Meta:
        verbose_name_plural = 'Itemimage'

    def __unicode__(self):
        return "Image"

class Feedback(models.Model):
    CATEGORY_CHOICE = (
        ('Feedback', 'feedback'),
        ('Suggestion', 'suggestion'),
        ('Complain', 'complain'),
        ('Other', 'other'),
    )
    name = models.CharField(_('Name'), max_length=50)
    category = models.CharField(_('Category'), choices=CATEGORY_CHOICE, max_length=25)
    description = models.TextField(_('Description'), max_length=200)

    class Meta:
        verbose_name_plural = 'Feedback'

    def __unicode__(self):
        return self.name

class Pincode(models.Model):
    city = models.CharField(_('City'), max_length=40)
    pincode = models.CharField(_('Pincode'), max_length=7, unique=True)

    class Meta:
        verbose_name_plural = 'Pincode'

    def __unicode__(self):
        return self.city

class Reviews(models.Model):
    RATING_CHOICES = (
        ('1', '1'),
        ('2', '2'),
        ('3', '3'),
        ('4', '4'),
        ('5', '5'),
    )
    user = models.ForeignKey(User)
    item = models.ForeignKey(Item)
    rating = models.CharField(_('Rating'), max_length=10, choices=RATING_CHOICES)
    review = models.TextField(_('Your Review'))
    confirmation = models.BooleanField(_('Confirmation of Admin'), default=False)

    class Meta:
        verbose_name_plural = 'Reviews'

    def __unicode__(self):
        return self.rating

class Deliveryaddress(models.Model):
    user = models.ForeignKey(User)
    name = models.CharField(_('Name'), max_length=30)
    pincode = models.CharField(_('Pincode'), max_length=7, unique=True)
    address = models.TextField(_('Address'))
    landmark = models.CharField(_('Lankmark'), max_length=30, blank=True, null=True)
    phone = models.CharField(_('Phone Number'), max_length=10)

    class Meta:
        verbose_name_plural = 'Delivery Address'

    def __unicode__(self):
        return self.name

app/templates/base.html
<!DOCTYPE html>
{% load bootstrap3 %}
{% load static %}
{% load carton_tags %}
<html>

<head>
    <title>Bong's Collection</title>
    {% block initialstatic %}
        <link href="{% static "css/bootstrap.min.css" %}" media="screen" rel="stylesheet">
        <link href="{% static "css/base.css" %}" media="screen" rel="stylesheet">
        <script src="{% static "js/base.js" %}"></script>
        <script src="{% static "js/jquery.min.js" %}"></script>
        <script src="{% static "js/bootstrap.min.js" %}"></script>
        <link rel="stylesheet" href="{% static 'nailthumb/jquery.nailthumb.1.1.css' %}" />
        <script src="{% static 'nailthumb/jquery.nailthumb.1.1.js' %}"></script>
    {% endblock %}
    {% block exinstatic %}

    {% endblock %}
</head>

<body>
    {% block navbar %}
    {% get_cart as cart %}
    <!-- Fixed navbar -->
    <div class="navbar navbar-default" id="fmeasure" style="background:#005387;border-radius:0;">
      <div class="col-lg-12" style="background:#005387;color:#fdd922" id="scroll">Your Suggestion and Support very much required to success the initiatives -- Bong Collection</div>
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".collapse-cus">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="/"><img class="connecting" src="{% static "images/logo.png" %}" width="350"/></a>
        </div>
        <div class="navbar-collapse collapse collapse-cus">
          <ul class="nav navbar-nav navbar-right">
            <li><a href="/feedback/">Feedback  or Suggestion</a></li>
            <li><a href="/accounts/signup/">Signup</a></li>
            <li id="size"><a href="/accounts/login/">Login</a></li>
          </ul>
        </div><!--/.nav-collapse -->
    </div>
    <!-- End fixed navbar -->
    <div class="navbar navbar-default navbar-custom" style="background:#0a3151;top:-1.5em;border-radius:0;border-top:0;;">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".collapse-custom">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
        </button>
      </div>
      <div class="navbar-collapse collapse collapse-custom">
          <ul class="nav navbar-nav">
            {% for category in categories %}
                <li><a href="/main/{{category.id}}/">{{category.category}}</a></li>
            {% endfor %}
          </ul>
          <div class="col-sm-1"></div>
          <div class="col-sm-4 col-md-4">
            <form class="navbar-form" role="search">
                <div class="input-group col-sm-12">
                    <input type="text" class="form-control search-input" placeholder="Search" name="q">
                    <div class="input-group-btn">
                        <button class="btn btn-default btn-search" type="submit"><i class="glyphicon glyphicon-search"></i></button>
                    </div>
                </div>
            </form>
          </div>
          <ul class="nav navbar-nav navbar-right">
            <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown" aria-expanded="false"><i class="glyphicon glyphicon-shopping-cart cart-color"></i> <b id="countCart">{{lencart}}</b> <b class="caret"></b></a>
                <ul class="dropdown-menu list-group">
                  {% for item in cart.items %}
                    <li class="list-group-item">
                        <div class="nailthumb-container square-thumb" style="display:inline;">
                          <img src="/media/{{ item.product.itemimage_set.all.0.image }}" />
                        </div><span style="font-size:10px;display:inline;">{{ item.product.item_name }}
                        <span class="badge">{{ item.quantity }}</span>
                      </span>
                    </li>
                  {% endfor %}
                  <li><a href="/cart/show/">Show Cart</a></li>
                </ul>
            </li>
        </ul>
      </div><!--/.nav-collapse -->
    </div>
    {% endblock %}

    {% block messages %}
    <div class="container indexing">
        {# Display django.contrib.messages as Bootstrap alerts #}
        {% bootstrap_messages %}
    </div>
    {% endblock %}

    {% block content %}

    {% endblock %}

    {% block footer %}
    <!-- Footer -->
    <br><br>
    <!-- Static bottom navbar -->
    <div class="navbar navbar-default navbar-fixed-bottom">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".bottom-collapse"> <!-- NOTE! data-target was changed to .bottom-collapse -->
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
        </div>
        <div class="navbar-collapse collapse bottom-collapse"> <!-- NOTE! The extra bottom-collapse class put on here -->
          <ul class="nav navbar-nav">
            <li><a href="#">About Us</a></li>
            <li><a href="#about">Terms & Policies</a></li>
            <li><a href="#contact">Contact Us</a></li>
          </ul><!-- 
          <ul class="nav navbar-nav navbar-right">
            <li><a href="../navbar/">Default</a></li>
            <li><a href="../navbar-fixed-top/">Fixed Bottom</a></li>
          </ul> -->
        </div><!--/.nav-collapse -->
      </div>
    </div>
    <!-- End Footer -->
    {% endblock %}

    {% block laststatic %}
        <!-- Go to www.addthis.com/dashboard to customize your tools -->
        <script type="text/javascript" src="//s7.addthis.com/js/300/addthis_widget.js#pubid=ra-54c41bda4f818b94" async="async"></script>
        <script type="text/javascript">
          $(document).ready(function() {
            $('.nailthumb-container').nailthumb();
          });
        </script>
        <style type="text/css">
        .square-thumb{
          width: 40px;
          height: 40px;
        }
        </style>
    {% endblock %}

    {% block exlastatic %}

    {% endblock %}
</body>
</html>

app/templates/catalog.html
{% extends "base.html" %}
{% load static %}

{% block content %}
    <div class="container">
        <div class="row">
            <div class="col-lg-3">
                <h3>Categories</h3>
                <ul class="list-group">
                    {% for subcategory in subcategories %}
                    <li class="list-group-item"><a href="/main/{{subcategory.id}}/">{{ subcategory }}</a></li>
                    {% endfor %}
                </ul>
                <hr>
                <h3>PRICE</h3>
                <div class="checkbox">
                  <label><input type="checkbox" value="">RS.499 And Below</label>
                </div>
                <div class="checkbox">
                  <label><input type="checkbox" value="">Rs.500-Rs.999</label>
                </div>
                <div class="checkbox">
                  <label><input type="checkbox" value="">Rs.1000-Rs.1499</label>
                </div>
                <div class="checkbox">
                  <label><input type="checkbox" value="">Rs.1500-Rs.1999</label>
                </div>
                <div class="checkbox">
                  <label><input type="checkbox" value="">Rs.2000-Rs.12499</label>
                </div>
                <div class="checkbox">
                  <label><input type="checkbox" value="">Rs.2500 And Above</label>
                </div>
            </div>
            <div class="col-lg-9 design">
                <h3 style="color:#0a3151"><strong>{{category.category}}</strong></h3>
                <p style="color:#0a3151">Items: All; Price Range: Max</p>
                <hr>
 
  <br>
  <!--       <div class="row">
            <div class="col-md-4">
                <div class="panel panel-primary" style="color:#0a3151;border-radius:0;">
                    <div style="margin: 10px;">
                    <img class="thumbnail img-responsive" alt="Bootstrap template" 
                        src="{% static "images/1.jpg" %}" />
                        <h4 class="text-center">Cypher Floored</h4>
                        <p class="text-center">Rs.49.99</p>
                    <a class="btn btn-sm btn-block btn-default" style="background-color:#fdd922; font-size:15px;color:#0a3151;border-radius:0; border-width: 3px;">ADD To Cart</a> 
                </div>
            </div>
            </div>
            <div class="col-md-4">
                <div class="panel panel-primary" style="color:#0a3151;border-radius:0;">
                    <div style="margin: 10px;">
                    <img class="thumbnail img-responsive" alt="Bootstrap template" 
                        src="{% static "images/1.jpg" %}" />
                        <h4 class="text-center">Cypher Floored</h4>
                        <p class="text-center">Rs.49.99</p>
                    <a class="btn btn-sm btn-block btn-default" style="background-color:#fdd922; font-size:15px;color:#0a3151;border-radius:0; border-width: 3px;">ADD To Cart</a> 
                </div>
            </div>
            </div>
            <div class="col-md-4">
                <div class="panel panel-primary" style="color:#0a3151;border-radius:0;">
                    <div style="margin: 10px;">
                    <img class="thumbnail img-responsive" alt="Bootstrap template" 
                        src="{% static "images/1.jpg" %}" />
                        <h4 class="text-center">Cypher Floored</h4>
                        <p class="text-center">Rs.49.99</p>
                    <a class="btn btn-sm btn-block btn-default" style="background-color:#fdd922; font-size:15px;color:#0a3151;border-radius:0; border-width: 3px;">ADD To Cart</a> 
                </div>
            </div>
            </div>
        </div> -->
        <div class="row">
            {% for item in finals %}
            <div class="col-md-4">
                <div class="panel panel-primary" style="color:#0a3151;border-radius:0;">
                    <div style="margin: 10px;">
                        <a href="/item/{{item.id}}/{{ item.price_set.all.0.fk_color.id }}/{{ item.price_set.all.0.fk_seller.id }}/">
                    <img class="thumbnail img-responsive" alt="Bootstrap template" 
                        src="/media/{{ item.itemimage_set.all.0.image }}" /></a>
                        <h4 class="text-center">{{ item.item_name }}</h4>
                        <p class="text-center">Rs. {{ item.price_set.all.0.price }}</p>
                    <a class="btn btn-sm btn-block btn-default addToCart" style="background-color:#fdd922; font-size:15px;color:#0a3151;border-radius:0; border-width: 3px;" href="/cart/add/?id={{boys.id}}">ADD To Cart</a> 
                    </div>
                </div>
            </div>
            {% endfor %}
<!--             <div class="col-md-4">
                <div class="panel panel-primary" style="color:#0a3151;border-radius:0;">
                    <div style="margin: 10px;">
                    <img class="thumbnail img-responsive" alt="Bootstrap template" 
                        src="{% static "images/1.jpg" %}" />
                        <h4 class="text-center">Cypher Floored</h4>
                        <p class="text-center">Rs.49.99</p>
                    <a class="btn btn-sm btn-block btn-default" style="background-color:#fdd922; font-size:15px;color:#0a3151;border-radius:0; border-width: 3px;">ADD To Cart</a>  
                </div>
            </div>
            </div>
            <div class="col-md-4">
                <div class="panel panel-primary" style="color:#0a3151;border-radius:0;">
                    <div style="margin: 10px;">
                    <img class="thumbnail img-responsive" alt="Bootstrap template" 
                        src="{% static "images/1.jpg" %}" />
                        <h4 class="text-center">Cypher Floored</h4>
                        <p class="text-center">Rs.49.99</p>
                    <a class="btn btn-sm btn-block btn-default" style="background-color:#fdd922; font-size:15px;color:#0a3151;border-radius:0; border-width: 3px;">ADD To Cart</a>  
                </div>
            </div>
            </div>
        </div> -->
<!--         <div class="row">
            <div class="col-md-4">
                <div class="panel panel-primary" style="color:#0a3151;border-radius:0;">
                    <div style="margin: 10px;">
                    <img class="thumbnail img-responsive" alt="Bootstrap template" 
                        src="{% static "images/1.jpg" %}" />
                        <h4 class="text-center">Cypher Floored</h4>
                        <p class="text-center">Rs.49.99</p>
                    <a class="btn btn-sm btn-block btn-default" style="background-color:#fdd922; font-size:15px;color:#0a3151;border-radius:0; border-width: 3px;">ADD To Cart</a>  
                </div>
            </div>
            </div>
            <div class="col-md-4">
                <div class="panel panel-primary" style="color:#0a3151;border-radius:0;">
                    <div style="margin: 10px;">
                    <img class="thumbnail img-responsive" alt="Bootstrap template" 
                        src="{% static "images/1.jpg" %}" />
                        <h4 class="text-center">Cypher Floored</h4>
                        <p class="text-center">Rs.49.99</p>
                    <a class="btn btn-sm btn-block btn-default" style="background-color:#fdd922; font-size:15px;color:#0a3151;border-radius:0; border-width: 3px;">ADD To Cart</a> 
                </div>
            </div>
            </div>
            <div class="col-md-4">
                <div class="panel panel-primary" style="color:#0a3151;border-radius:0;">
                    <div style="margin: 10px;">
                    <img class="thumbnail img-responsive" alt="Bootstrap template" 
                        src="{% static "images/1.jpg" %}" />
                        <h4 class="text-center">Cypher Floored</h4>
                        <p class="text-center">Rs.49.99</p>
                    <a class="btn btn-sm btn-block btn-default" style="background-color:#fdd922; font-size:15px;color:#0a3151;border-radius:0; border-width: 3px;">ADD To Cart</a> 
                </div>
            </div>
            </div>
        </div> -->
    </div>
<!-- <div class="pagination">
    <span class="step-links">
        {% if finals.has_previous %}
            <a href="?page={{ finals.previous_page_number }}">previous</a>
        {% endif %}

        <span class="current">
            Page {{ finals.number }} of {{ finals.paginator.num_pages }}.
        </span>

        {% if finals.has_next %}
            <a href="?page={{ finals.next_page_number }}">next</a>
        {% endif %}
    </span>
</div> -->

    <ul class="pager">
        {% if finals.has_previous %}
        <li class="previous"><a href="?page={{ finals.previous_page_number }}">← Previous</a></li>
          {% endif %}
        <li class="current">
            Page {{ finals.number }} of {{ finals.paginator.num_pages }}.
        </li>          
          {% if finals.has_next %}
          <li class="next"><a href="?page={{ finals.next_page_number }}">Next →</a></li>
          {% endif %}
    </ul>
  </div>
</div>
</div>
    <style type="text/css">
    hr {
        -moz-border-bottom-colors: none;
        -moz-border-image: none;
        -moz-border-left-colors: none;
        -moz-border-right-colors: none;
        -moz-border-top-colors: none;
        border-color: #0a3151 -moz-use-text-color #0a3151;
        border-style: solid none;
        border-width: 2px 0;
        margin: 18px 0;
    }
    .design{
        border-left: 1px solid #0a3151;
    }
    </style>
    <script>
    $(".addToCart").click(function(e)
    {
        var formURL = $(this).attr("href");
        $.ajax(
        {
            url : formURL,
            type: "GET",
            success:function(data, textStatus, jqXHR) 
            {
                $("#countCart").text(data);
            },
            error: function(jqXHR, textStatus, errorThrown) 
            {
                alert('[Error] Please try Again');
            }
        });
        e.preventDefault(); //STOP default action
    });
    </script>
{% endblock %}

app/templates/home.html
{% extends "base.html" %}
{% load static %}

{% block content %}

<!-- Start Caraousel -->
<div class="container">
    <div id="carousel1" class="carousel slide" data-ride="carousel">
        <div class="carousel-inner">
            <div class="item active">
                <img alt="Bootstrap template" src="http://placehold.it/1200x400/b4d9a7/ffffff&text=Company Information">
                <div class="carousel-caption">
                    <!-- <h3>Company information</h3>
                    <p>
                        Founded in 1892 and headquartered in Fairfield, CT, General Electric Company (LSE; NYSE: GE) 
                        is a technology and financial services company. 
                        The company offers products and services ranging from aircraft engines, 
                        power generation, water processing, and household appliances, among others.
                    </p> -->
                </div>
            </div>
            <div class="item">
                <img alt="Bootstrap template" src="http://placehold.it/1200x400/4f77cb/ffffff&text=Social">
                <div class="carousel-caption">
                    <!-- <div class="col-lg-12 text-center v-center" style="font-size: 39pt;">
                        <a href="#"><span class="avatar"><i class="fa fa-google-plus"></i></span></a>
                        <a href="#"><span class="avatar"><i class="fa fa-linkedin"></i></span></a>
                        <a href="#"><span class="avatar"><i class="fa fa-facebook"></i></span></a>
                        <a href="#"><span class="avatar"><i class="fa fa-github"></i></span></a>
                    </div> -->
                </div>
            </div>
            <div class="item">
                <img alt="Bootstrap template" src="http://placehold.it/1200x400/d11e4f/ffffff&text=Portfolio">
                <div class="carousel-caption">
                    <!-- <h3>Portfolio</h3>
                    <p>
                        This is a list of some of the work done by the company over the past quarter. 
                    </p> -->
                </div>
            </div>
        </div>
        <ul class="nav nav-pills nav-justified">
            <li data-target="#carousel1" data-slide-to="0" class="active">
                <a href="#">About<small>Lorem ipsum dolor sit</small></a>
            </li>
            <li data-target="#carousel1" data-slide-to="1">
                <a href="#">Projects<small>Lorem ipsum dolor sit</small></a>
            </li>
            <li data-target="#carousel1" data-slide-to="2">
                <a href="#">Portfolio<small>Lorem ipsum dolor sit</small></a>
            </li>
        </ul>
    </div>
</div>
<!-- End Carousel -->

<!-- Moving Box Carousel -->
<div class="container">
<div class="col-md-12 heading"><h2><u>New Arrivals for Men & Boys</u></h2></div>
<div class="col-md-12 ">
<div class="carousel slide" id="myCarousel">
  <br>
  <div class="carousel-inner">
    {% for arrival in final %}
        {% if forloop.first %}
    <div class="item active aitem">
      <div class="col-xs-3"><a href="/item/{{arrival.id}}/{{ arrival.price_set.all.0.fk_color.id }}/{{ arrival.price_set.all.0.fk_seller.id }}/"><img src="/media/{{ arrival.itemimage_set.all.0.image }}" class="img-responsive"></a></div>
    </div>
    {% else %}
    <div class="item aitem">
      <div class="col-xs-3"><a href="/item/{{arrival.id}}/{{ arrival.price_set.all.0.fk_color.id }}/{{ arrival.price_set.all.0.fk_seller.id }}/"><img src="/media/{{ arrival.itemimage_set.all.0.image }}" class="img-responsive"></a></div>
    </div>
    {% endif %}
    {% endfor %}
<!--     <div class="item aitem">
      <div class="col-xs-3"><a href="#"><img src="/static/images/placehold.gif" class="img-responsive"></a></div>
    </div>
    <div class="item aitem">
      <div class="col-xs-3"><a href="#"><img src="/static/images/placehold.gif" class="img-responsive"></a></div>
    </div>
    <div class="item aitem">
      <div class="col-xs-3"><a href="#"><img src="/static/images/placehold.gif" class="img-responsive"></a></div>
    </div>
    <div class="item aitem">
      <div class="col-xs-3"><a href="#"><img src="/static/images/placehold.gif" class="img-responsive"></a></div>
    </div>
    <div class="item aitem">
      <div class="col-xs-3"><a href="#"><img src="/static/images/placehold.gif" class="img-responsive"></a></div>
    </div>
    <div class="item aitem">
      <div class="col-xs-3"><a href="#"><img src="/static/images/placehold.gif" class="img-responsive"></a></div>
    </div> -->
  </div>
  <br>
  <a class="left carousel-control" href="#myCarousel" data-slide="prev"><i class="glyphicon glyphicon-chevron-left"></i></a>
  <a class="right carousel-control" href="#myCarousel" data-slide="next"><i class="glyphicon glyphicon-chevron-right"></i></a>
</div>
</div>
</div>
<!-- End Moving Box Carousel -->

<!-- Moving Box Carousel -->
<div class="container">
<div class="col-md-12 heading"><h2><u>New Arrivals for Womens & Girls</u></h2></div>
<div class="col-md-12 ">
<div class="carousel slide" id="myCarousel1">
  <br>
  <div class="carousel-inner">
    {% for arrivals in final1 %}
        {% if forloop.first %}
    <div class="item active bitem">
      <div class="col-xs-3"><a href="/item/{{arrivals.id}}/{{ arrivals.price_set.all.0.fk_color.id }}/{{ arrivals.price_set.all.0.fk_seller.id }}/"><img src="/media/{{ arrivals.itemimage_set.all.0.image }}" class="img-responsive"></a></div>
    </div>
    {% else %}
    <div class="item bitem">
      <div class="col-xs-3"><a href="/item/{{arrivals.id}}/{{ arrivals.price_set.all.0.fk_color.id }}/{{ arrivals.price_set.all.0.fk_seller.id }}/"><img src="/media/{{ arrivals.itemimage_set.all.0.image }}" class="img-responsive"></a></div>
    </div>
    {% endif %}
    {% endfor %}
<!--     <div class="item active bitem">
      <div class="col-xs-3"><a href="#"><img src="/static/images/placehold.gif" class="img-responsive"></a></div>
    </div>
  <div class="item bitem">
      <div class="col-xs-3"><a href="#"><img src="/static/images/placehold.gif" class="img-responsive"></a></div>
    </div>
    <div class="item bitem">
      <div class="col-xs-3"><a href="#"><img src="/static/images/placehold.gif" class="img-responsive"></a></div>
    </div>
    <div class="item bitem">
      <div class="col-xs-3"><a href="#"><img src="/static/images/placehold.gif" class="img-responsive"></a></div>
    </div>
    <div class="item bitem">
      <div class="col-xs-3"><a href="#"><img src="/static/images/placehold.gif" class="img-responsive"></a></div>
    </div>
    <div class="item bitem">
      <div class="col-xs-3"><a href="#"><img src="/static/images/placehold.gif" class="img-responsive"></a></div>
    </div>
    <div class="item bitem">
      <div class="col-xs-3"><a href="#"><img src="/static/images/placehold.gif" class="img-responsive"></a></div>
    </div>
    <div class="item bitem">
      <div class="col-xs-3"><a href="#"><img src="/static/images/placehold.gif" class="img-responsive"></a></div>
    </div> -->
  </div>
  <a class="left carousel-control" href="#myCarousel1" data-slide="prev"><i class="glyphicon glyphicon-chevron-left"></i></a>
  <a class="right carousel-control" href="#myCarousel1" data-slide="next"><i class="glyphicon glyphicon-chevron-right"></i></a>
</div>
</div>
</div>
<!-- End Moving Box Carousel -->
{% endblock %}
{% block exlastatic %}
    <link href="{% static "css/home.css" %}" media="screen" rel="stylesheet">
    <script src="{% static "js/home.js" %}"></script>
{% endblock %}
</body>
</html>